customShips = {
    'Red-M0nk3ySMShip1': {"name": "Ship1", "desc": "From MetConst", "author": "Red-M0nk3y"},
    'Red-M0nk3ySMShip2': {"name": "Ship2", "desc": "From MetConst", "author": "Red-M0nk3y"},
    'Red-M0nk3ySMShip3': {"name": "Ship3", "desc": "From MetConst", "author": "Red-M0nk3y"},
    'Red-M0nk3ySMShip4': {"name": "Ship4", "desc": "From MetConst", "author": "Red-M0nk3y"},
    'Red-M0nk3ySMShip5': {"name": "Zero Mission Ship", "desc": "From MetConst", "author": "Red-M0nk3y"},
    'opposition_ship': {"name": "Opposition Ship", "desc": "From Opposition Hack", "author": "mccad00"},
    'ascent_ship': {"name": "Ascent Ship", "desc": "From Ascent Hack", "author": "Benox50"},
    'ice_metal_ship': {"name": "Ice Metal Uninstall", "desc": "From Ice Metal Uninstall Hack", "author": "Crys"},
    'MFFusionship': {"name": "Fusion Ship", "desc": "Fusion Ship from Metconst", "author": "Crys"},
    'lost_world_ship': {"name": "Lost World", "desc": "From Lost World Hack", "author": "TROM"},
    'hyperion_ship': {"name": "Hyperion", "desc": "From Hyperion Hack", "author": "silverpaw84"},
    'phazon_ship': {"name": "Phazon", "desc": "From Phazon Hack", "author": "Red-M0nk3y"},
    'mario_ship': {"name": "Mario Ship", "desc": "For Mario and Luigi sprites", "author": "mccad00"},
    'top_hunter_ship': {"name": "Top Hunter", "desc": "From Top Hunter: Roddy & Cathy", "author": "theonlydude"},
    'am2r_ship': {"name": "AM2R", "desc": "From AM2R", "author": "AM2R & theonlydude"},
    'lastresort_ship': {"name": "Last Resort", "desc": "From Last Resort", "author": "theonlydude", "hideSamus": True},
    'metalslug_ship': {"name": "Metal Slug", "desc": "From Metal Slug", "author": "theonlydude", "showSamusAtTakeoff": True},
    'xwing': {"name": "Crossed Wing", "desc": "Generic ship which happen to have wings in the shape of an X", "author": "theonlydude", "hideSamus": True},
    'the_baby': {"name": "The Baby", "desc": "It's the Baby !", "author": "Chrono", "hideSamus": True},
    'pocket_rocket': {"name": "Pocket Rocket", "desc": "Groovy !", "author": "Fredz00z"},
    'kirbyship': {"name": "Kirby Ship", "desc": "For Kirby sprite", "author": "Fredz00z"},
    'minitroid_ship': {"name": "Minitroid", "desc": "From Minitroid", "author": "Fredz00z & Chrono"},
    'enterprise': {"name": "USS Enterprise", "desc": "From Star Trek", "author": "Chrono", "hideSamus": True}
}

customShipsOrder = [
    'Red-M0nk3ySMShip5',
    'MFFusionship',
    'opposition_ship',
    'ascent_ship',
    'am2r_ship',
    'mario_ship',
    'the_baby',
    'top_hunter_ship',
    'lastresort_ship',
    'metalslug_ship',
    'pocket_rocket',
    'kirbyship',
    'minitroid_ship',
    'hyperion_ship',
    'phazon_ship',
    'lost_world_ship',
    'ice_metal_ship',
    'Red-M0nk3ySMShip1',
    'Red-M0nk3ySMShip2',
    'Red-M0nk3ySMShip3',
    'Red-M0nk3ySMShip4',
    'xwing',
    'enterprise'
]
